Don't include malloc.h
This header is unused and non-standard.

Fixes:

    In file included from src/tmperamental.c:35:0:
    /usr/include/malloc.h:3:2: error: #error "<malloc.h> has been replaced by <stdlib.h>"

on FreeBSD.